import { Movie } from '@/types/movie';

export const moviesTrendingData: Movie[] = [
  {
    id: 1,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 2,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 3,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 4,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 5,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 6,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 7,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 8,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 9,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 10,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 11,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 12,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 13,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 14,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 15,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 16,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 17,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 18,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 19,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 20,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 21,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 22,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 23,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 24,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 25,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 26,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 27,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 28,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 29,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 30,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 31,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 32,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 33,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 34,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 35,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 36,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 37,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 38,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 39,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 40,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 41,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 42,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 43,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 44,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 45,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 46,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 47,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
  {
    id: 48,
    title: 'Major Thunder',
    src: '/images/hero/posters/poster.jpg',
    alt: 'Poster',
    rating: 9.5,
    year: 2018,
    director: 'Katsuhiro Otomo',
    actors: 'Mitsuo Iwata,Nozomu Sasaki,Mami Koyama,Mami Koyama',
    genre: ['sci-fi', 'comedy', 'drama'],
    description:
      "In 2019, following a world war triggered by the sudden destruction of Tokyo on July 16, 1988, Neo-Tokyo is plagued by corruption, anti-government protests, terrorism, and gang violence. During a violent rally, the hot-headed Shōtarō Kaneda leads his vigilante bōsōzoku gang, the Capsules, against the rival Clown gang. Kaneda's best friend, Tetsuo Shima, inadvertently crashes his motorcycle into Takashi, an esper who escaped from a government laboratory with the aid of a resistance organization. Assisted by fellow esper Masaru, Japan Self-Defense Forces Colonel Shikishima recaptures Takashi, has Tetsuo hospitalized, and arrests the Capsules. While being interrogated by the police, Kaneda meets Kei, an activist within the resistance movement, and tricks the authorities into releasingher with his gang",
  },
];
